=== tranaweera/ark-informatics/tags/wager2.0.3/wager_lab/ant/{deploy.classesdir}/neuragenix/genix/data_interface/Casegenix-0.1.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--

Casegenix DTD.
Copyright 2004 Neuragenix Pty. Ltd.

Created by Long Tran, Oct 2004


-->


<!ELEMENT casegenix (CORECASE*, CASEDIARY*)>

<!-- +++++++++++ CORECASE +++++++++++ -->

<!ELEMENT CORECASE_intCoreCaseKey (#PCDATA)>
<!ELEMENT CORECASE_intParentCaseKey (#PCDATA)>
<!ELEMENT CORECASE_intAssignedToKey (#PCDATA)>
<!ELEMENT CORECASE_strCategory (#PCDATA)>
<!ELEMENT CORECASE_strSubCategory (#PCDATA)>
<!ELEMENT CORECASE_strBranchPriority (#PCDATA)>
<!ELEMENT CORECASE_strOffence (#PCDATA)>
<!ELEMENT CORECASE_strCHSID (#PCDATA)>
<!ELEMENT CORECASE_strFileNo (#PCDATA)>
<!ELEMENT CORECASE_intCaseID (#PCDATA)>
<!ELEMENT CORECASE_strReferenceID (#PCDATA)>
<!ELEMENT CORECASE_strConfidential (#PCDATA)>
<!ELEMENT CORECASE_strPriority (#PCDATA)>
<!ELEMENT CORECASE_strCreatedDate (#PCDATA)>
<!ELEMENT CORECASE_strOccurrenceDate (#PCDATA)>
<!ELEMENT CORECASE_strReceivedDate (#PCDATA)>
<!ELEMENT CORECASE_strSource (#PCDATA)>
<!ELEMENT CORECASE_strDetection (#PCDATA)>
<!ELEMENT CORECASE_strSummary (#PCDATA)>
<!ELEMENT CORECASE_strStatus (#PCDATA)>
<!ELEMENT CORECASE_dblSavings (#PCDATA)>
<!ELEMENT CORECASE_dblRecovery (#PCDATA)>
<!ELEMENT CORECASE_dblLegalCosts (#PCDATA)>
<!ELEMENT CORECASE_dblRestitution (#PCDATA)>
<!ELEMENT CORECASE_dblAwardedCosts (#PCDATA)>
<!ELEMENT CORECASE_dblFines (#PCDATA)>
<!ELEMENT CORECASE_strComments (#PCDATA)>
<!ELEMENT CORECASE_intBPriorityFlag (#PCDATA)>
<!ELEMENT CORECASE_intGroupKey (#PCDATA)>
<!ELEMENT CORECASE_strClaimNumber (#PCDATA)>
<!ELEMENT CORECASE ( CORECASE_intCoreCaseKey, 
	CORECASE_intParentCaseKey, 
	CORECASE_intAssignedToKey, 
	CORECASE_strCategory, 
	CORECASE_strSubCategory, 
	CORECASE_strBranchPriority, 
	CORECASE_strOffence, 
	CORECASE_strCHSID, 
	CORECASE_strFileNo, 
	CORECASE_intCaseID, 
	CORECASE_strReferenceID, 
	CORECASE_strConfidential, 
	CORECASE_strPriority, 
	CORECASE_strCreatedDate, 
	CORECASE_strOccurrenceDate, 
	CORECASE_strReceivedDate, 
	CORECASE_strSource, 
	CORECASE_strDetection, 
	CORECASE_strSummary, 
	CORECASE_strStatus, 
	CORECASE_dblSavings, 
	CORECASE_dblRecovery, 
	CORECASE_dblLegalCosts, 
	CORECASE_dblRestitution, 
	CORECASE_dblAwardedCosts, 
	CORECASE_dblFines, 
	CORECASE_strComments, 
	CORECASE_intBPriorityFlag, 
	CORECASE_intGroupKey, 
	CORECASE_strClaimNumber )>
        
<!ATTLIST CORECASE
        type (insert|update|delete) "insert">
        
<!-- +++++++++++ END CORECASE +++++++++++ -->

<!-- +++++++++++ CASEDIARY +++++++++++ -->

<!ELEMENT CASEDIARY_intCaseDiaryKey (#PCDATA)>
<!ELEMENT CASEDIARY_intCoreCaseKey (#PCDATA)>
<!ELEMENT CASEDIARY_strDate (#PCDATA)>
<!ELEMENT CASEDIARY_strTime (#PCDATA)>
<!ELEMENT CASEDIARY_strAction (#PCDATA)>
<!ELEMENT CASEDIARY_strTimeTakenHour (#PCDATA)>
<!ELEMENT CASEDIARY_strTimeTakenMin (#PCDATA)>
<!ELEMENT CASEDIARY_strStatus (#PCDATA)>
<!ELEMENT CASEDIARY_strPriority (#PCDATA)>
<!ELEMENT CASEDIARY_strBranchPriority (#PCDATA)>
<!ELEMENT CASEDIARY_strOwner (#PCDATA)>
<!ELEMENT CASEDIARY_intSaved (#PCDATA)>
<!ELEMENT CASEDIARY ( CASEDIARY_intCaseDiaryKey, 
	CASEDIARY_intCoreCaseKey, 
	CASEDIARY_strDate, 
	CASEDIARY_strTime, 
	CASEDIARY_strAction, 
	CASEDIARY_strTimeTakenHour, 
	CASEDIARY_strTimeTakenMin, 
	CASEDIARY_strStatus, 
	CASEDIARY_strPriority, 
	CASEDIARY_strBranchPriority, 
	CASEDIARY_strOwner, 
	CASEDIARY_intSaved )>
        
<!ATTLIST CASEDIARY
        type (insert|update|delete) "insert">        

<!-- +++++++++++ END CASEDIARY +++++++++++ -->

<!-- +++++++++++ RELATEDCASE +++++++++++ -->

<!ELEMENT RELATEDCASE_intRelatedCaseKey (#PCDATA)>
<!ELEMENT RELATEDCASE_intPartiesKey (#PCDATA)>
<!ELEMENT RELATEDCASE_intCaseKey (#PCDATA)>
<!ELEMENT RELATEDCASE_strRelationship (#PCDATA)>
<!ELEMENT RELATEDCASE ( RELATEDCASE_intRelatedCaseKey, 
	RELATEDCASE_intPartiesKey, 
	RELATEDCASE_intCaseKey, 
	RELATEDCASE_strRelationship )>

<!-- +++++++++++ END RELATEDCASE +++++++++++ -->

<!-- +++++++++++ RELATEDPARTIES +++++++++++ -->

<!ELEMENT RELATEDPARTIES_intPartiesKey (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strID (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strType (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strSubType (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strName (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strTitle (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strFirstName (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strLastName (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strDOB (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strSex (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strEmail (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strJobTitle (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strFaxAreaCode (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strFaxNumber (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strMobile (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strPhoneAreaCode (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strPhoneNumber (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strRelationship (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strStreetNumber (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strAddress (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strSuburb (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strState (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strPostcode (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strCountry (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strDescription (#PCDATA)>
<!ELEMENT RELATEDPARTIES_intRemuneration (#PCDATA)>
<!ELEMENT RELATEDPARTIES_intNoOfEmployees (#PCDATA)>
<!ELEMENT RELATEDPARTIES_strWICCode (#PCDATA)>
<!ELEMENT RELATEDPARTIES ( RELATEDPARTIES_intPartiesKey, 
	RELATEDPARTIES_strID, 
	RELATEDPARTIES_strType, 
	RELATEDPARTIES_strSubType, 
	RELATEDPARTIES_strName, 
	RELATEDPARTIES_strTitle, 
	RELATEDPARTIES_strFirstName, 
	RELATEDPARTIES_strLastName, 
	RELATEDPARTIES_strDOB, 
	RELATEDPARTIES_strSex, 
	RELATEDPARTIES_strEmail, 
	RELATEDPARTIES_strJobTitle, 
	RELATEDPARTIES_strFaxAreaCode, 
	RELATEDPARTIES_strFaxNumber, 
	RELATEDPARTIES_strMobile, 
	RELATEDPARTIES_strPhoneAreaCode, 
	RELATEDPARTIES_strPhoneNumber, 
	RELATEDPARTIES_strRelationship, 
	RELATEDPARTIES_strStreetNumber, 
	RELATEDPARTIES_strAddress, 
	RELATEDPARTIES_strSuburb, 
	RELATEDPARTIES_strState, 
	RELATEDPARTIES_strPostcode, 
	RELATEDPARTIES_strCountry, 
	RELATEDPARTIES_strDescription, 
	RELATEDPARTIES_intRemuneration, 
	RELATEDPARTIES_intNoOfEmployees, 
	RELATEDPARTIES_strWICCode )>

<!-- +++++++++++ END RELATEDPARTIES +++++++++++ -->

<!-- +++++++++++ ASSIGNMENT +++++++++++ -->

<!ELEMENT ASSIGNMENT_intAssignmentKey (#PCDATA)>
<!ELEMENT ASSIGNMENT_intCaseKey (#PCDATA)>
<!ELEMENT ASSIGNMENT_intUserKey (#PCDATA)>
<!ELEMENT ASSIGNMENT_strAssignedDate (#PCDATA)>
<!ELEMENT ASSIGNMENT_strReAssignedDate (#PCDATA)>
<!ELEMENT ASSIGNMENT ( ASSIGNMENT_intAssignmentKey, 
	ASSIGNMENT_intCaseKey, 
	ASSIGNMENT_intUserKey, 
	ASSIGNMENT_strAssignedDate, 
	ASSIGNMENT_strReAssignedDate )>

<!-- +++++++++++ END ASSIGNMENT +++++++++++ -->

=== tranaweera/ark-informatics/tags/wager2.0.4/wager_lab/stylesheets/neuragenix/genix/data_interface/dtd-check.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : dtd-check.xml
    Created on : 6 December 2004, 14:56
    Author     : ltran
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE casegenix SYSTEM 'Casegenix-0.1.dtd'>
<casegenix>

<CASEDIARY type="insert">
    <CASEDIARY_intCaseDiaryKey>1</CASEDIARY_intCaseDiaryKey>
	<CASEDIARY_intCoreCaseKey>2</CASEDIARY_intCoreCaseKey>
	<CASEDIARY_strDate>1</CASEDIARY_strDate>
	<CASEDIARY_strTime>1</CASEDIARY_strTime>
	<CASEDIARY_strAction>2</CASEDIARY_strAction>
	<CASEDIARY_strTimeTakenHour>2</CASEDIARY_strTimeTakenHour>
	<CASEDIARY_strTimeTakenMin/>
	<!--CASEDIARY_strStatus>3</CASEDIARY_strStatus-->
	<CASEDIARY_strPriority>3</CASEDIARY_strPriority>
	<CASEDIARY_strBranchPriority>3</CASEDIARY_strBranchPriority>
	<CASEDIARY_strOwner>3</CASEDIARY_strOwner>
	<CASEDIARY_intSaved>3</CASEDIARY_intSaved>
</CASEDIARY>    

</casegenix>
